spring:
  application:
    name: choerodon-fnd-iam
  datasource:
    url: jdbc:mysql://localhost:3306/iam_service_upgrade?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
logging:
  level:
    io.choerodon.iam: debug
mybatis:
  identity: JDBC
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
db:
  type: mysql
server:
  port: 8080
management:
  server:
    port: 8031
  endpoints:
    web:
      exposure:
        include: '*'
