spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iam_service_upgrade?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  profiles:
    active: @activatedProperties@ #取pom.profiles.profile.id=run的activatedProperties
logging:
  level:
    io.choerodon.iam: debug
mybatis:
  identity: JDBC
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
db:
  type: mysql

