spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iam_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

choerodon:
  devops:
    message: true
  eureka:
    event:
      max-cache-size: 300
      retry-time: 5
      retry-interval: 3
      skip-services: config**, **register-server, **gateway**, zipkin**, hystrix**, oauth**
  saga:
    consumer:
      enabled: false # 启动消费端
      thread-num: 2 # saga消息消费线程池大小
      max-poll-size: 200 # 每次拉取消息最大数量
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
  schedule:
    consumer:
      enabled: false # 启用任务调度消费端
      thread-num: 1 # 任务调度消费线程数
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
  cleanPermission: false
logging:
  level:
    io.choerodon.iam: debug
eureka:
  client:
    enabled: false
